# -*- coding: utf-8 -*-
"""Dice_Roller.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14YaMw8YUL45TVSFn4yBt5LaU8-KCqp33
"""

import random

def roll_dice(num_dice, sides):
    total_roll = 0
    for _ in range(num_dice):
        roll = random.randint(1, sides)
        total_roll += roll
        print(f"You rolled a {roll}")
    return total_roll

def dice_roller():
    while True:
        try:
            num_dice = int(input("Enter the number of dice you want to roll: "))
            sides = int(input("Enter the number of sides on the dice: "))
            if num_dice > 0 and sides > 0:
                total_roll = roll_dice(num_dice, sides)
                print(f"You rolled a total of {total_roll}")
                roll_again = input("Do you want to roll again? (y/n): ").lower()
                if roll_again != 'y':
                    break
            else:
                print("Please enter positive integers only.")
        except ValueError:
            print("Please enter a valid integer.")

if __name__ == "__main__":
    dice_roller()