# -*- coding: utf-8 -*-
"""Number_Guessing _Game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12yh0OEAs9tgZlkXQy6De6rtb6nrB832P
"""

import random

randNumber = random.randint(1, 100)
# print(randNumber)

userGuess = None
name = input("Enter your name: ")
print("Welcome " + name)
guesses = 0

while userGuess != randNumber:
    userGuess = int(input("Enter your guess: "))
    guesses = guesses + 1
    if guesses <= 10:  # The maximum number of guesses condition should be outside the loop
        if userGuess == randNumber:
            print("Congratulations! You guessed it right...")
        elif userGuess < randNumber:
            print("Good try, go higher")
        else:
            print("Oops, you crossed it, go lower")
    else:
        print("Maximum number of attempts reached. Try again.")
        break  # Exit the loop when the maximum attempts are reached.

print(f"You got the number at your {guesses} guess, Congratulations")