# -*- coding: utf-8 -*-
"""To_do_list.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pn_aSCEUMPxWKEGSrSk04fxdQgTpmjzV
"""

class ToDoList:
    def __init__(self):
        self.tasks = []

    def add_task(self, task):
        self.tasks.append(task)

    def delete_task(self, task):
        if task in self.tasks:
            self.tasks.remove(task)

    def view_tasks(self):
        for task in self.tasks:
            print(task)


def run():
    to_do_list = ToDoList()

    while True:
        print("\n1. Add Task")
        print("2. Delete Task")
        print("3. View Tasks")
        print("4. Quit")

        try:
            choice = int(input("Enter choice: "))
        except ValueError:
            print("Invalid input. Please enter an integer.")
            continue

        if choice == 1:
            task = input("Enter task: ")
            to_do_list.add_task(task)
        elif choice == 2:
            task = input("Enter task to delete: ")
            to_do_list.delete_task(task)
        elif choice == 3:
            to_do_list.view_tasks()
        elif choice == 4:
            print("Quitting...")
            break
        else:
            print("Invalid choice. Please enter a number between 1 and 4.")


if __name__ == "__main__":
    run()